import { verifyPassURIOffline } from "./main";
import mineDIDDocument from "./mineDIDDocument.json";


const PATRICK_1_PASS = "NZCP:/1/2KCEPIQEIIYDCAJGUBMQCH5FAF4B4ZDJMQ5HOZLCHJXHUY3QFZRW65TJMQYTSLTIMVQWY5DIFZXHUBA2MO5T6BQFDJQ5UC4GA5IA33GGYDRPERINRHQ3AMZOLCPSYYTWMOSGQQDDN5XHIZLYOSBHQJTIOR2HA4Z2F4XXO53XFZ3TGLTPOJTS6MRQGE4C6Y3SMVSGK3TUNFQWY4ZPOYYXQKTIOR2HA4Z2F4XW46TDOAXGG33WNFSDCOJONBSWC3DUNAXG46RPMNXW45DFPB2HGL3WGFYWG4TFMRSW45DJMFWFG5LCNJSWG5FDMNSG6YTKGE4TMMBNGA2C2MJWNJTGC3LJNR4U4YLNMVSFG5DBOJUWO2LWMVXE4YLNMVTVAYLUOJUWG23EOR4XAZMCORLGK4TJMZUWCYTMMVBXEZLEMVXHI2LBNRXVA5LCNRUWGQ3POZUWIUDBONZWO5TFOJZWS33OMUYS4MBOGBMEBPT7R252WX6NX7IL2MVG36JG5NRZK5BE2H53DDVDUGJXDGNEYAB5DXCIOG4E5NRSDSI3F5ABJCEOLZL76427NM7POQG46ES6ND2V3GMQ===="

const PATRICK_2_PASS = "NZCP:/1/2KCEPIQEIIYDCAJGUBMQCH5FAF4B4ZDJMQ5HOZLCHJXHUY3QFZRW65TJMQYTSLTIMVQWY5DIFZXHUBA2MO5T6BQFDJQ5UC4GA5IA33GGYDRPERINRHQ3AMZOLCPSYYTWMOSGQQDDN5XHIZLYOSBHQJTIOR2HA4Z2F4XXO53XFZ3TGLTPOJTS6MRQGE4C6Y3SMVSGK3TUNFQWY4ZPOYYXQKTIOR2HA4Z2F4XW46TDOAXGG33WNFSDCOJONBSWC3DUNAXG46RPMNXW45DFPB2HGL3WGFYWG4TFMRSW45DJMFWFG5LCNJSWG5FDMNSG6YTKGE4TMMBNGA2C2MJWNJTGC3LJNR4U4YLNMVSFG5DBOJUWO2LWMVXE4YLNMVTVAYLUOJUWG23EOR4XAZMCORLGK4TJMZUWCYTMMVBXEZLEMVXHI2LBNRXVA5LCNRUWGQ3POZUWIUDBONZWO5TFOJZWS33OMUYS4MBOGBMEBKBZ2PWB4B6KBSOYXQQM6FXCW327HOLOLSMEHLMYQHCIEIX6SCWIHO5ZLXBBIIOELNL55LHMFYG4ASJSFODWMIBD7JAAJIMWBMYU7DFQ===="


test("PATRICK_1_PASS is successful", async () => {
  const result = await verifyPassURIOffline(PATRICK_1_PASS, {
    trustedIssuer: mineDIDDocument.id,
    didDocument: mineDIDDocument,
  });
  // console.log('result', result);
  expect(result.success).toBe(true);
  expect(result.credentialSubject?.givenName).toBe("Patrick");
  expect(result.credentialSubject?.familyName).toBe("Star");

});
  

test("PATRICK_2_PASS is successful", async () => {
  const result = await verifyPassURIOffline(PATRICK_2_PASS, {
    trustedIssuer: mineDIDDocument.id,
    didDocument: mineDIDDocument,
  });
  // console.log('result', result);
  expect(result.success).toBe(true);
  expect(result.credentialSubject?.givenName).toBe("Patrick");
  expect(result.credentialSubject?.familyName).toBe("Star");

});
