import { DID_DOCUMENTS, verifyPassURIOffline } from "./main";


const PATRICK_1_PASS = "NZCP:/1/2KCEHIIBE2QQIQRQGFMQCH5FAF4B4ZDJMQ5HOZLCHJXHUY3QFZRW65TJMQYTSLTIMVQWY5DIFZXHUBA2MO5T6BQFDJQ5UC4GA5IA33GGYDRPERINRHQ3AMZOLCPSYYTWMOSGQQDDN5XHIZLYOSBHQJTIOR2HA4Z2F4XXO53XFZ3TGLTPOJTS6MRQGE4C6Y3SMVSGK3TUNFQWY4ZPOYYXQKTIOR2HA4Z2F4XW46TDOAXGG33WNFSDCOJONBSWC3DUNAXG46RPMNXW45DFPB2HGL3WGFYWG4TFMRSW45DJMFWFG5LCNJSWG5FDMNSG6YTKGE4TMMBNGA2C2MJWNJTGC3LJNR4U4YLNMVSFG5DBOJUWO2LWMVXE4YLNMVTVAYLUOJUWG23EOR4XAZMCORLGK4TJMZUWCYTMMVBXEZLEMVXHI2LBNRXVA5LCNRUWGQ3POZUWIUDBONZWO5TFOJZWS33OMUYS4MBOGBMEA72XCADQRSOODBOGIP46TL2E5TYRDD3PWEXFU2OQ7HUWRD2FDOVLPP7ZXY3H2ITZAWVN44JZF74PKO7EXJGLBIYTXJ5L4VNULTAEJVOQ===="

const PATRICK_2_PASS = "NZCP:/1/2KCEHIIBE2QQIQRQGFMQCH5FAF4B4ZDJMQ5HOZLCHJXHUY3QFZRW65TJMQYTSLTIMVQWY5DIFZXHUBA2MO5T6BQFDJQ5UC4GA5IA33GGYDRPERINRHQ3AMZOLCPSYYTWMOSGQQDDN5XHIZLYOSBHQJTIOR2HA4Z2F4XXO53XFZ3TGLTPOJTS6MRQGE4C6Y3SMVSGK3TUNFQWY4ZPOYYXQKTIOR2HA4Z2F4XW46TDOAXGG33WNFSDCOJONBSWC3DUNAXG46RPMNXW45DFPB2HGL3WGFYWG4TFMRSW45DJMFWFG5LCNJSWG5FDMNSG6YTKGE4TMMBNGA2C2MJWNJTGC3LJNR4U4YLNMVSFG5DBOJUWO2LWMVXE4YLNMVTVAYLUOJUWG23EOR4XAZMCORLGK4TJMZUWCYTMMVBXEZLEMVXHI2LBNRXVA5LCNRUWGQ3POZUWIUDBONZWO5TFOJZWS33OMUYS4MBOGBMEBT6TQADYIMQ6OIQ4N2SZXBXT47F2D4RIIPWYRRASUOOY3WRRX7UYHAQ2GAN7YBPTRESPTXEFUSALFXXNA5IILLCDWNO7ORTXHZL6PLAQ===="


test("PATRICK_1_PASS is successful", async () => {
  const result = await verifyPassURIOffline(PATRICK_1_PASS, {
    trustedIssuer: DID_DOCUMENTS.MINE.id,
    didDocument: DID_DOCUMENTS.MINE,
  });
  // console.log('result', result);
  expect(result.success).toBe(true);
  expect(result.credentialSubject?.givenName).toBe("Patrick");
  expect(result.credentialSubject?.familyName).toBe("Star");

});
  

test("PATRICK_2_PASS is successful", async () => {
  const result = await verifyPassURIOffline(PATRICK_2_PASS, {
    trustedIssuer: DID_DOCUMENTS.MINE.id,
    didDocument: DID_DOCUMENTS.MINE,
  });
  // console.log('result', result);
  expect(result.success).toBe(true);
  expect(result.credentialSubject?.givenName).toBe("Patrick");
  expect(result.credentialSubject?.familyName).toBe("Star");

});
